### ISSUE TITLE
No backend found on macOS even with `metal` feature enabled

### ISSUE THREAD

**Issue by Phrohdoh** [cloudhead/rx#12]
```shell
$ git rev-parse HEAD
0d9cf727eb755bddd0b2fdf78cfea9545ce91ff2

$ cargo --version
cargo 1.37.0 (9edd08916 2019-08-02)

$ rustc --version
rustc 1.37.0 (eae3437df 2019-08-13)

$ RUST_BACKTRACE=1 cargo run --features="metal"
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/rx`
thread 'main' panicked at 'no backend found for this platform!', src/platform/dummy.rs:47:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::begin_panic
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/panicking.rs:411
   8: rx::platform::backend::init
             at src/platform/dummy.rs:47
   9: rx::platform::init
             at src/platform/mod.rs:21
  10: rx::init
             at ./src/lib.rs:73
  11: rx::main
             at src/main.rs:17
  12: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  13: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  14: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  15: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  16: std::panicking::try
             at src/libstd/panicking.rs:275
  17: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  18: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  19: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  20: rx::main
```

**Comment by cloudhead** [comment]
Yeah, on current master you have to enable a windowing platform, eg. `winit`. So it would be `--features=winit,metal`.

This will eventually be detected automatically.

**Comment by cloudhead** [comment]
Closing, let me know if you still have issues.
