### ISSUE TITLE
Linux crash on many frames opened

### ISSUE THREAD

**Issue by niktob560** [cloudhead/rx#37]
Opened ~20 frames with ``:f/clone`` to draw a simple snake, used without savings, editor crashed  
trace:  
  
```
thread 'main' panicked at 'assertion failed: `(left == right)`  
  left: `Ok(false)`,  
 right: `Ok(true)`: GPU got stuck on a frame (image 2) :(', /home/nikto_b/.cargo/registry  /src/github.com-1ecc6299db9ec823/wgpu-native-0.3.3/src/swap_chain.rs:190:5  
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.  
thread 'main' panicked at 'assertion failed: `(left == right)`  
  left: `Ok(false)`,  
 right: `Ok(true)`: GPU got stuck :(', /home/nikto_b/.cargo/registry/src/github.com-  1ecc6299db9ec823/wgpu-native-0.3.3/src/device.rs:204:13  
stack backtrace:  
   0:     0x55c44b312064 - backtrace::backtrace::libunwind::trace::h9c615d6efbf938f6  
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37  /src/backtrace/libunwind.rs:88  
   1:     0x55c44b312064 - backtrace::backtrace::trace_unsynchronized::hfaa1ce1a28b26657  
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37  /src/backtrace/mod.rs:66  
   2:     0x55c44b312064 - std::sys_common::backtrace::_print_fmt::h1b66ca12d17b932b  
                               at src/libstd/sys_common/backtrace.rs:77  
   3:     0x55c44b312064 - <std::sys_common::backtrace::_print::DisplayBacktrace as   core::fmt::Display>::fmt::hb788f286135c56c2  
                               at src/libstd/sys_common/backtrace.rs:61  
   4:     0x55c44b332e6c - core::fmt::write::h07fe3dc5621915ed  
                               at src/libcore/fmt/mod.rs:1028  
   5:     0x55c44b30ef37 - std::io::Write::write_fmt::h01232d256c58655a  
                               at src/libstd/io/mod.rs:1412  
   6:     0x55c44b31433e - std::sys_common::backtrace::_print::h28f8e2b4d9e94458  
                               at src/libstd/sys_common/backtrace.rs:65  
   7:     0x55c44b31433e - std::sys_common::backtrace::print::hd186282d73d3e408  
                               at src/libstd/sys_common/backtrace.rs:50  
   8:     0x55c44b31433e - std::panicking::default_hook::{{closure}}::h924d5d525cfaa28b  
                               at src/libstd/panicking.rs:189  
   9:     0x55c44b314041 - std::panicking::default_hook::hcf10145036a31ca0  
                               at src/libstd/panicking.rs:206  
  10:     0x55c44b3149d5 - std::panicking::rust_panic_with_hook::h0d1ccf594ba2c25f  
                               at src/libstd/panicking.rs:469  
  11:     0x55c44b314572 - std::panicking::continue_panic_fmt::hd9914224a5c73476  
                               at src/libstd/panicking.rs:376  
  12:     0x55c44b3144cc - std::panicking::begin_panic_fmt::h21a179276bc3d2a5  
                               at src/libstd/panicking.rs:331  
  13:     0x55c44b23d284 -   wgpu_native::device::Device <gfx_backend_vulkan::Backend>::maintain::hb86857300ab924e6  
  14:     0x55c44b24b7c6 - wgpu_device_poll  
  15:     0x55c44b0f5ad8 - core::ptr::real_drop_in_place::h573d63d1ea18404b  
  16:     0x55c44b0f4985 - rx::platform::run::hbca45d375a106e3e  
  17:     0x55c44b0e42f7 - rx::init::h1770aa72b933b02c  
  18:     0x55c44b0f978c - rx::main::h02e3fd22fc5109fe  
  19:     0x55c44b0f4e53 - std::rt::lang_start::{{closure}}::h0d34df9be9aebcc3  
  20:     0x55c44b314403 - std::rt::lang_start_internal::{{closure}}::h9d93058f2363250f  
                               at src/libstd/rt.rs:48  
  21:     0x55c44b314403 - std::panicking::try::do_call::h3396b203c650aa3f  
                               at src/libstd/panicking.rs:288  
  22:     0x55c44b31705a - __rust_maybe_catch_panic  
                               at src/libpanic_unwind/lib.rs:80  
  23:     0x55c44b314ecd - std::panicking::try::hd95abb921899f84c  
                               at src/libstd/panicking.rs:267  
  24:     0x55c44b314ecd - std::panic::catch_unwind::h067f8f58c3aff594  
                               at src/libstd/panic.rs:396  
  25:     0x55c44b314ecd - std::rt::lang_start_internal::hc2ec29100191f803  
                               at src/libstd/rt.rs:47  
  26:     0x55c44b0f9a42 - main  
  27:     0x7faeecc09153 - __libc_start_main  
  28:     0x55c44b0e398e - _start  
  29:                0x0 - <unknown>  
thread panicked while panicking. aborting.  
[1]    2243857 illegal hardware instruction (core dumped)  rx  
```

System:  
ArchLinux on Linux 5.4.0  
Intel Corporation UHD Graphics 620 (rev 07)  
sway version 1.2

**Comment by cloudhead** [comment]
Thanks, this looks like it could be a bug in the underlying library `wgpu`. Since it's due for an update, I will look into it after the update.
